/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.login;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.event.WindowListener;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author nerea.salgado
 */
public class LoginJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginJDialog.class.getName());

    /**
     * Creates new form LoginJDialog
     */
    public LoginJDialog(boolean modal, Frame parent) {
        super(parent, modal);
        initComponents();
        applyStyles();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginImagenJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        PasswordJField = new javax.swing.JPasswordField();
        passwordJLabel = new javax.swing.JLabel();
        forgetPasswordJLabel = new javax.swing.JLabel();
        loginJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        userLoginJPanel = new javax.swing.JPanel();
        loginInitUserName = new javax.swing.JLabel();
        loginInitUserEmail = new javax.swing.JLabel();
        backToLectureJButton = new javax.swing.JButton();
        loginInitUserRol = new javax.swing.JLabel();
        logOutJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loginImagenJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        emailJLabel.setText("Email:");

        emailJTextField.addActionListener(this::emailJTextFieldActionPerformed);

        PasswordJField.addActionListener(this::PasswordJFieldActionPerformed);

        passwordJLabel.setText("Contraseña:");

        forgetPasswordJLabel.setText("¿Has olvidado la contraseña?");

        loginJButton.setText("Iniciar Sesión");
        loginJButton.addActionListener(this::loginJButtonActionPerformed);

        cancelJButton.setText("Cancelar");
        cancelJButton.addActionListener(this::cancelJButtonActionPerformed);

        loginInitUserName.setText("Name");
        loginInitUserName.setToolTipText("");
        loginInitUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        loginInitUserEmail.setText("Email");
        loginInitUserEmail.setToolTipText("");
        loginInitUserEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backToLectureJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecturas.png"))); // NOI18N

        loginInitUserRol.setText("Rol");
        loginInitUserRol.setToolTipText("");
        loginInitUserRol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logOutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cerrarsesion.png"))); // NOI18N
        logOutJButton.setText("Cerrar Sesión");

        javax.swing.GroupLayout userLoginJPanelLayout = new javax.swing.GroupLayout(userLoginJPanel);
        userLoginJPanel.setLayout(userLoginJPanelLayout);
        userLoginJPanelLayout.setHorizontalGroup(
            userLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLoginJPanelLayout.createSequentialGroup()
                        .addComponent(loginInitUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(backToLectureJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(userLoginJPanelLayout.createSequentialGroup()
                        .addGroup(userLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginInitUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginInitUserRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        userLoginJPanelLayout.setVerticalGroup(
            userLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLoginJPanelLayout.createSequentialGroup()
                        .addComponent(loginInitUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginInitUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginInitUserRol, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userLoginJPanelLayout.createSequentialGroup()
                        .addComponent(backToLectureJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(logOutJButton)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginImagenJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordJLabel)
                            .addComponent(emailJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(PasswordJField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(userLoginJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(forgetPasswordJLabel)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginImagenJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordJLabel))
                .addGap(18, 18, 18)
                .addComponent(forgetPasswordJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(cancelJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLoginJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void PasswordJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordJFieldActionPerformed

    private void emailJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJTextFieldActionPerformed

    public void addWindwosListener(WindowListener windowListener) {
        super.addWindowListener(windowListener);
    }

    public void addLogOutJButtonActionListener(ActionListener al) {
        this.logOutJButton.addActionListener(al);
    }

    public void setVisibleLoginJButton(boolean visible) {
        this.loginJButton.setVisible(visible);
    }

    public void setVisibleCancelJbutton(boolean visible) {
        this.cancelJButton.setVisible(visible);
    }

    public void setVisibleEmailJTextField(boolean visible) {
        this.emailJTextField.setVisible(visible);
    }

    public void setVisibleLabelEmail(boolean visible) {
        this.emailJLabel.setVisible(visible);
    }

    public void setVisibleLabelPassword(boolean visible) {
        this.passwordJLabel.setVisible(visible);
    }

    public void setVisiblePasswordJTextField(boolean visible) {
        this.PasswordJField.setVisible(visible);
    }

    public void setVisibleForgetPasswordJLabel(boolean visible) {
        this.forgetPasswordJLabel.setVisible(visible);
    }

    public void setVisibleUserLoginJPanel(boolean visible) {
        this.userLoginJPanel.setVisible(visible);
    }

    public void setUserNameLoginJLabel(String text) {
        this.loginInitUserName.setText(text);
    }

    public void setUserEmailLoginJLabel(String text) {
        this.loginInitUserEmail.setText(text);
    }

    public void setUserEmailLoginJTextField(String text) {
        this.emailJTextField.setText(text);
    }

    public void setUserRolLoginJLabel(String text) {
        this.loginInitUserRol.setText(text);
    }

    public void setTamanhoImage(int width, int height) {
        loginImagenJLabel.setSize(width, height);
    }

    public void setVisibleBackToLectureJButton(boolean visible) {
        this.backToLectureJButton.setVisible(visible);
    }

    public void getImagetoLabel(ImageIcon image) {
        int desiredWidth = 100;
        int desiredHeight = 100;

        Image newImage = image.getImage().getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
        loginImagenJLabel.setIcon(new ImageIcon(newImage));
    }

    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        cancelJButton.setBackground(new Color(247, 181, 181));
        cancelJButton.setForeground(Color.BLACK);
        cancelJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButton.setFocusPainted(false);
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        loginJButton.setBackground(new Color(180, 225, 180));
        loginJButton.setForeground(Color.BLACK);
        loginJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        loginJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        loginJButton.setFocusPainted(false);
        loginJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        logOutJButton.setBackground(new Color(196, 97, 27));
        logOutJButton.setForeground(Color.BLACK);
        logOutJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        logOutJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        logOutJButton.setFocusPainted(false);
        logOutJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        backToLectureJButton.setBackground(new Color(225, 251, 252));
        backToLectureJButton.setForeground(Color.BLACK);
        backToLectureJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        backToLectureJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        backToLectureJButton.setFocusPainted(false);
        backToLectureJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);

        emailJLabel.setFont(labelFont);
        passwordJLabel.setFont(labelFont);
        forgetPasswordJLabel.setFont(labelFont);
        loginInitUserName.setFont(labelFont);
        loginInitUserEmail.setFont(labelFont);
        loginInitUserRol.setFont(labelFont);

        forgetPasswordJLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        forgetPasswordJLabel.setForeground(new Color(134, 134, 134));
        loginInitUserName.setFont(labelFont);

        emailJTextField.setFont(labelFont);
        emailJTextField.setBackground(blanco);
        emailJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        PasswordJField.setFont(labelFont);
        PasswordJField.setBackground(blanco);
        PasswordJField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        getContentPane().setBackground(grisFondo);

    }

    public void addForgetPasswordActionListener(MouseListener moul) {
        this.forgetPasswordJLabel.addMouseListener(moul);
    }

    public void addBackToLectureJButton(ActionListener al) {
        this.backToLectureJButton.addActionListener(al);
    }

    public void addCancelButtonActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void addLoginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }

    public String getEmailJTextField() {
        return this.emailJTextField.getText();
    }

    public String getPasswordJPassword() {
        return new String(this.PasswordJField.getPassword());
    }

    public void setPasswordJField(String password) {
        this.PasswordJField.setText(password);
    }

    public void clearFields() {
        emailJTextField.setText("");
        PasswordJField.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordJField;
    private javax.swing.JButton backToLectureJButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel forgetPasswordJLabel;
    private javax.swing.JButton logOutJButton;
    private javax.swing.JLabel loginImagenJLabel;
    private javax.swing.JLabel loginInitUserEmail;
    private javax.swing.JLabel loginInitUserName;
    private javax.swing.JLabel loginInitUserRol;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPanel userLoginJPanel;
    // End of variables declaration//GEN-END:variables
}
