/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.books;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import view.student.StudentJDialog;
import view.teacher.TeacherJDialog;

/**
 *
 * @author Nerea
 */
public class BooksJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BooksJDialog.class.getName());

    /**
     * Creates new form BoosJDialog
     */
    public BooksJDialog(boolean modal, StudentJDialog view) {
        super(view, modal);
        initComponents();
        applyStyles();
        int rowISBN = booksTable.getColumnCount() - 1;
        booksTable.getColumnModel().getColumn(rowISBN).setMinWidth(0);
        booksTable.getColumnModel().getColumn(rowISBN).setMaxWidth(0);
        booksTable.getColumnModel().getColumn(rowISBN).setWidth(0);
    }

    public BooksJDialog(boolean modal, JDialog view) {
        super(view, modal);
        initComponents();
        applyStyles();
        int rowISBN = booksTable.getColumnCount() - 1;
        booksTable.getColumnModel().getColumn(rowISBN).setMinWidth(0);
        booksTable.getColumnModel().getColumn(rowISBN).setMaxWidth(0);
        booksTable.getColumnModel().getColumn(rowISBN).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        addBookToListJbutton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        recomendJButton = new javax.swing.JButton();
        edadFilterJComboBox = new javax.swing.JComboBox<>();
        tematicaJComboBox = new javax.swing.JComboBox<>();
        filterGeneroJComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lista libros disponibles en la biblioteca");

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Género", "Temática", "Edad", "Ejemplar", "Editorial", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(booksTable);

        addBookToListJbutton.setText("Añadir");

        cancelJButton.setText("Salir");

        recomendJButton.setText("Recomendar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addBookToListJbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recomendJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(filterGeneroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tematicaJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addComponent(edadFilterJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tematicaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterGeneroJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadFilterJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookToListJbutton)
                    .addComponent(recomendJButton)
                    .addComponent(cancelJButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.booksTable.getModel();
        model.addRow(row);
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.booksTable.getModel();
        model.setRowCount(0);
        booksTable.clearSelection();
        booksTable.revalidate();
        booksTable.repaint();
    }

    public void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        cancelJButton.setBackground(new Color(247, 181, 181));
        cancelJButton.setForeground(Color.BLACK);
        cancelJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButton.setFocusPainted(false);
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        addBookToListJbutton.setBackground(new Color(180, 225, 180));
        addBookToListJbutton.setForeground(Color.BLACK);
        addBookToListJbutton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        addBookToListJbutton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addBookToListJbutton.setFocusPainted(false);
        addBookToListJbutton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        recomendJButton.setBackground(new Color(180, 225, 180));
        recomendJButton.setForeground(Color.BLACK);
        recomendJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        recomendJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        recomendJButton.setFocusPainted(false);
        recomendJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);
        filterGeneroJComboBox.setFont(labelFont);
        filterGeneroJComboBox.setBorder(BorderFactory.createLineBorder(grisBorde));
        filterGeneroJComboBox.setBackground(blanco);

        tematicaJComboBox.setFont(labelFont);
        tematicaJComboBox.setBorder(BorderFactory.createLineBorder(grisBorde));
        tematicaJComboBox.setBackground(blanco);
        
        edadFilterJComboBox.setFont(labelFont);
        edadFilterJComboBox.setBorder(BorderFactory.createLineBorder(grisBorde));
        edadFilterJComboBox.setBackground(blanco);
    }

    public void setVisibleRecomendJButton(boolean visible) {
        this.recomendJButton.setVisible(visible);
    }

    public void setVisibleAddBookToListJButton(boolean visible) {
        this.addBookToListJbutton.setVisible(visible);
    }

    public String getInfo(int row, int col) {
        return booksTable.getValueAt(row, col).toString();
    }

    public int getSelectedRow() {
        int select = booksTable.getSelectedRow();
        return select;
    }

    public int getSelectedCol() {
        int select = booksTable.getSelectedColumn();
        return select;
    }

    public void addBookToListJbuttonActionListener(ActionListener al) {
        this.addBookToListJbutton.addActionListener(al);
    }

    public void addCancelJButton(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void addRecomendJButton(ActionListener al) {
        this.recomendJButton.addActionListener(al);
    }

    public void addfilterGeneroJComboBox(String nombreCurso) {
        this.filterGeneroJComboBox.addItem(nombreCurso);
    }

    public void clearFilterGeneroJComboBox() {
        this.filterGeneroJComboBox.removeAllItems();
    }

    public String getFilterGeneroJComboBox() {
        return this.filterGeneroJComboBox.getSelectedItem().toString();
    }

    public void addGeneroJComboBoxActionListener(ActionListener al) {
        this.filterGeneroJComboBox.addActionListener(al);
    }

    public void addTematicaJComboBox(String nombreCurso) {
        this.tematicaJComboBox.addItem(nombreCurso);
    }

    public void clearTematicaJComboBox() {
        this.tematicaJComboBox.removeAllItems();
    }

    public String getTematicaJComboBox() {
        return this.tematicaJComboBox.getSelectedItem().toString();
    }

    public void addTematicaJComboBoxActionListener(ActionListener al) {
        this.tematicaJComboBox.addActionListener(al);
    }

    public void addEdadFilterJComboBoxString(String nombreCurso) {
        this.edadFilterJComboBox.addItem(nombreCurso);
    }

    public void clearEdadFilterJComboBoxString() {
        this.edadFilterJComboBox.removeAllItems();
    }

    public String getEdadFilterJComboBoxString() {
        return this.edadFilterJComboBox.getSelectedItem().toString();
    }

    public void addEadFilterJComboBoxActionListener(ActionListener al) {
        this.edadFilterJComboBox.addActionListener(al);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookToListJbutton;
    private javax.swing.JTable booksTable;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JComboBox<String> edadFilterJComboBox;
    private javax.swing.JComboBox<String> filterGeneroJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recomendJButton;
    private javax.swing.JComboBox<String> tematicaJComboBox;
    // End of variables declaration//GEN-END:variables
}
