/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.addData;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;

/**
 *
 * @author nerea.salgado
 */
public class AddEditDataBooksJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEditDataBooksJDialog.class.getName());

    /**
     * Creates new form addDataBooks
     */
    public AddEditDataBooksJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataBookTitleJLabel = new javax.swing.JLabel();
        isbnJLabel = new javax.swing.JLabel();
        isbnJTextField = new javax.swing.JTextField();
        tituloJLabel = new javax.swing.JLabel();
        tituloJTextField = new javax.swing.JTextField();
        autorJLabel = new javax.swing.JLabel();
        autorJTextField = new javax.swing.JTextField();
        generoJLabel = new javax.swing.JLabel();
        generoJTextField = new javax.swing.JTextField();
        tematicaJLabel = new javax.swing.JLabel();
        tematicaJTextField = new javax.swing.JTextField();
        edadRecomenadadaJLabel = new javax.swing.JLabel();
        edadRecomendadaJTextField = new javax.swing.JTextField();
        ejemplaresJLabel = new javax.swing.JLabel();
        ejemplaresJTextField = new javax.swing.JTextField();
        editorialJLabel = new javax.swing.JLabel();
        editorialJTextField = new javax.swing.JTextField();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dataBookTitleJLabel.setText("Datos libro");

        isbnJLabel.setText("ISBN:");

        tituloJLabel.setText("Título:");

        autorJLabel.setText("Autor:");

        generoJLabel.setText("Género:");

        tematicaJLabel.setText("Temática:");

        edadRecomenadadaJLabel.setText("Edad recomendada:");

        ejemplaresJLabel.setText("Ejemplares:");

        editorialJLabel.setText("Editorial:");

        saveJButton.setText("Guardar");

        cancelJButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloJLabel)
                    .addComponent(isbnJLabel)
                    .addComponent(autorJLabel)
                    .addComponent(generoJLabel)
                    .addComponent(tematicaJLabel)
                    .addComponent(edadRecomenadadaJLabel)
                    .addComponent(ejemplaresJLabel)
                    .addComponent(editorialJLabel))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isbnJTextField)
                    .addComponent(tituloJTextField)
                    .addComponent(autorJTextField)
                    .addComponent(generoJTextField)
                    .addComponent(tematicaJTextField)
                    .addComponent(editorialJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejemplaresJTextField)
                    .addComponent(edadRecomendadaJTextField))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dataBookTitleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(saveJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelJButton)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dataBookTitleJLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isbnJLabel)
                            .addComponent(isbnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloJLabel)
                            .addComponent(tituloJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autorJLabel)
                            .addComponent(autorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generoJLabel)
                            .addComponent(generoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tematicaJLabel)
                            .addComponent(tematicaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edadRecomenadadaJLabel)
                            .addComponent(edadRecomendadaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ejemplaresJLabel)
                            .addComponent(ejemplaresJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editorialJLabel)
                            .addComponent(editorialJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelJButton)
                            .addComponent(saveJButton))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        Color azulAccion = new Color(164, 196, 235);
        Color amarilloValor = new Color(249, 231, 159);
        Color verde = new Color(168, 230, 207);
        Color naranjaUpdate = new Color(253, 203, 164);
        Color rojoBorrar = new Color(247, 181, 181);
        Color grisDetalles = new Color(213, 216, 220);
        Color grisFiltros = new Color(200, 200, 200);

        cancelJButton.setBackground(rojoBorrar);
        cancelJButton.setForeground(Color.BLACK);
        cancelJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButton.setFocusPainted(false);
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        saveJButton.setBackground(verde);
        saveJButton.setForeground(Color.BLACK);
        saveJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        saveJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        saveJButton.setFocusPainted(false);
        saveJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);

        dataBookTitleJLabel.setFont(labelFont);
        dataBookTitleJLabel.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        isbnJTextField.setFont(labelFont);
        isbnJLabel.setFont(labelFont);
        isbnJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        tituloJTextField.setFont(labelFont);
        tituloJLabel.setFont(labelFont);
        tituloJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        autorJTextField.setFont(labelFont);
        autorJLabel.setFont(labelFont);
        autorJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        generoJTextField.setFont(labelFont);
        generoJLabel.setFont(labelFont);
        generoJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        tematicaJTextField.setFont(labelFont);
        tematicaJLabel.setFont(labelFont);
        tematicaJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        edadRecomendadaJTextField.setFont(labelFont);
        edadRecomenadadaJLabel.setFont(labelFont);
        edadRecomendadaJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        ejemplaresJTextField.setFont(labelFont);
        ejemplaresJLabel.setFont(labelFont);
        ejemplaresJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        editorialJTextField.setFont(labelFont);
        editorialJLabel.setFont(labelFont);
        editorialJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        getContentPane().setBackground(grisFondo);
    }

    public String getISBNJTextField() {
        return this.isbnJTextField.getText();
    }

    public void setISBNTextField(String isbn) {
        this.isbnJTextField.setText(isbn);
    }

    public String getAutorJTextField() {
        return this.autorJTextField.getText();
    }

    public void setAutorTextField(String nombreAutor) {
        this.autorJTextField.setText(nombreAutor);
    }

    public String getTituloJTextField() {
        return this.tituloJTextField.getText();
    }

    public void setTituloJTextField(String titulo) {
        this.tituloJTextField.setText(titulo);
    }

    public String getGeneroJTextField() {
        return this.generoJTextField.getText();
    }

    public void setGeneroJTextField(String genero) {
        this.generoJTextField.setText(genero);
    }

    public String getTematicaJTextField() {
        return this.tematicaJTextField.getText();
    }

    public void setTematicaJTextField(String tematica) {
        this.tematicaJTextField.setText(tematica);
    }

    public String getEdadRecomendadaJTextField() {
        return this.edadRecomendadaJTextField.getText();
    }

    public void setEdadRecomendadaJTextField(String edadRecomendada) {
        this.edadRecomendadaJTextField.setText(edadRecomendada);
    }

    public String getEjemplaresJTextField() {
        return this.ejemplaresJTextField.getText();
    }

    public void setEjemplaresJTextField(String ejemplares) {
        this.ejemplaresJTextField.setText(ejemplares);
    }

    public String getEditorialJTextField() {
        return this.editorialJTextField.getText();
    }

    public void setEditorialJTextField(String ejemplares) {
        this.editorialJTextField.setText(ejemplares);
    }

    public void addSaveJButtonActionListener(ActionListener al) {
        this.saveJButton.addActionListener(al);
    }

    public void addCancelJButtonActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void setIsbnJTextFieldEditable(boolean editable) {
        this.isbnJTextField.setEditable(editable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorJLabel;
    private javax.swing.JTextField autorJTextField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel dataBookTitleJLabel;
    private javax.swing.JLabel edadRecomenadadaJLabel;
    private javax.swing.JTextField edadRecomendadaJTextField;
    private javax.swing.JLabel editorialJLabel;
    private javax.swing.JTextField editorialJTextField;
    private javax.swing.JLabel ejemplaresJLabel;
    private javax.swing.JTextField ejemplaresJTextField;
    private javax.swing.JLabel generoJLabel;
    private javax.swing.JTextField generoJTextField;
    private javax.swing.JLabel isbnJLabel;
    private javax.swing.JTextField isbnJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel tematicaJLabel;
    private javax.swing.JTextField tematicaJTextField;
    private javax.swing.JLabel tituloJLabel;
    private javax.swing.JTextField tituloJTextField;
    // End of variables declaration//GEN-END:variables
}
