/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.addData;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import view.login.LoginJDialog;

/**
 *
 * @author Nerea
 */
public class AddEditDataUserAdminJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEditDataUserAdminJDialog.class.getName());

    /**
     * Creates new form DataUserJDialog
     */
    public AddEditDataUserAdminJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataUserJLabel = new javax.swing.JLabel();
        nameUserJLabel = new javax.swing.JLabel();
        nameUserJTextField = new javax.swing.JTextField();
        secondLastNameUserJLabel = new javax.swing.JLabel();
        secondLastNameUserJTextField = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        passwordJPassword = new javax.swing.JPasswordField();
        emailJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        rolJLabel = new javax.swing.JLabel();
        rolJComboBox = new javax.swing.JComboBox<>();
        departamentoJComboBox = new javax.swing.JComboBox<>();
        curseJComboBox = new javax.swing.JComboBox<>();
        departamentoJLabel = new javax.swing.JLabel();
        cursoJLabel = new javax.swing.JLabel();
        telefonoJLabel = new javax.swing.JLabel();
        telefonoJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dataUserJLabel.setText("Datos Usuario");

        nameUserJLabel.setText("Nombre");

        secondLastNameUserJLabel.setText("Apellidos");

        emailJLabel.setText("Correo");

        passwordJLabel.setText("Contraseña");

        saveJButton.setText("Guardar");

        cancelJButton.setText("Cancelar");

        rolJLabel.setText("Rol:");

        rolJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona un rol--", "SuperAdmin", "gestor", "Profesor", "reparador", "alumno" }));

        departamentoJLabel.setText("Departamento:");

        cursoJLabel.setText("Curso:");

        telefonoJLabel.setText("Teléfono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rolJLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(secondLastNameUserJLabel)
                                        .addComponent(nameUserJLabel)
                                        .addComponent(emailJLabel)
                                        .addComponent(passwordJLabel))
                                    .addComponent(departamentoJLabel)
                                    .addComponent(cursoJLabel)
                                    .addComponent(telefonoJLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(saveJButton)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordJPassword)
                            .addComponent(emailJTextField)
                            .addComponent(secondLastNameUserJTextField)
                            .addComponent(nameUserJTextField)
                            .addComponent(departamentoJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rolJComboBox, 0, 332, Short.MAX_VALUE)
                            .addComponent(curseJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefonoJTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataUserJLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataUserJLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameUserJLabel)
                    .addComponent(nameUserJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondLastNameUserJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondLastNameUserJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJLabel)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolJLabel)
                    .addComponent(rolJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefonoJLabel)
                    .addComponent(telefonoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cursoJLabel))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveJButton)
                            .addComponent(cancelJButton)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departamentoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(departamentoJLabel)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;
        
        Color azulAccion = new Color(164, 196, 235);
        Color amarilloValor = new Color(249, 231, 159);
        Color verde = new Color(168, 230, 207);
        Color naranjaUpdate = new Color(253, 203, 164);
        Color rojoBorrar = new Color(247, 181, 181);
        Color grisDetalles = new Color(213, 216, 220);
        Color grisFiltros = new Color(200, 200, 200);
        
        cancelJButton.setBackground(rojoBorrar);
        cancelJButton.setForeground(Color.BLACK);
        cancelJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButton.setFocusPainted(false);
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        saveJButton.setBackground(verde);
        saveJButton.setForeground(Color.BLACK);
        saveJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        saveJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        saveJButton.setFocusPainted(false);
        saveJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);
        
        nameUserJLabel.setFont(labelFont);
        passwordJLabel.setFont(labelFont);
        emailJLabel.setFont(labelFont);
        dataUserJLabel.setFont(labelFont);
        secondLastNameUserJLabel.setFont(labelFont);
        rolJLabel.setFont(labelFont);
        departamentoJLabel.setFont(labelFont);
        cursoJLabel.setFont(labelFont);
        telefonoJLabel.setFont(labelFont);
        
        nameUserJTextField.setFont(labelFont);
        nameUserJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        
        secondLastNameUserJTextField.setBackground(blanco);
        secondLastNameUserJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        
        emailJTextField.setBackground(blanco);
        emailJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        
        passwordJPassword.setBackground(blanco);
        passwordJPassword.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        
        telefonoJTextField.setBackground(blanco);
        telefonoJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        
        getContentPane().setBackground(grisFondo);
        
    }
    
    public String getNameUserJTextField() {
        return this.nameUserJTextField.getText();
    }
    
    public String getSecondLastNameUserJTextField() {
        return this.secondLastNameUserJTextField.getText();
    }
    
    public String getEmailJTextField() {
        return this.emailJTextField.getText();
    }
    
    public void setEmailJTextField(String email) {
        this.emailJTextField.setText(email);
    }
    
    public String getPasswordJTextField() {
        return new String(this.passwordJPassword.getPassword());
    }
    
    public void setPasswordJTextField(String password) {
        this.passwordJPassword.setText(password);
    }
    
    public void setSecondLastNameUserJTextField(String secondLasName) {
        this.secondLastNameUserJTextField.setText(secondLasName);
    }
    
    public void setNameUserJTextField(String name) {
        this.nameUserJTextField.setText(name);
    }
    
    public void addSaveActionListener(ActionListener al) {
        this.saveJButton.addActionListener(al);
    }
    
    public void addCancelActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }
    
    public void clear() {
        nameUserJTextField.setText("");
        secondLastNameUserJTextField.setText("");
        emailJTextField.setText("");
        passwordJPassword.setText("");
    }
    
    public void addItemsrolJComboBox(String nombreCurso) {
        this.rolJComboBox.addItem(nombreCurso);
    }
    
    public void clearRolJComboBox() {
        this.rolJComboBox.removeAllItems();
    }
    
    public String getRolJComboBox() {
        return this.rolJComboBox.getSelectedItem().toString();
    }
    
    public void setRolJComboBox(String rol) {
        this.rolJComboBox.setSelectedItem(rol);
    }
    
    public void addDepartamentoJComboBox(String nombreCurso) {
        this.departamentoJComboBox.addItem(nombreCurso);
    }
    
    public void clearDepartamentoJComboBox() {
        this.departamentoJComboBox.removeAllItems();
    }
    
    public String getDepartamentoJComboBox() {
        return this.departamentoJComboBox.getSelectedItem().toString();
    }
    
    public void setDepartamentoJComboBox(String rol) {
        this.departamentoJComboBox.setSelectedItem(rol);
    }
    
    public void addCurseJComboBox(String nombreCurso) {
        this.curseJComboBox.addItem(nombreCurso);
    }
    
    public void clearCurseJComboBox() {
        this.curseJComboBox.removeAllItems();
    }
    
    public String getCurseJComboBox() {
        return this.curseJComboBox.getSelectedItem().toString();
    }
    
    public void setCurseJComboBox(String rol) {
        this.curseJComboBox.setSelectedItem(rol);
    }
    
    public void setVisibleDepartamentoJComboBox(boolean visible) {
        this.departamentoJComboBox.setVisible(visible);
    }
    
    public void setVisibleDepartamentoJLabel(boolean visible) {
        this.departamentoJLabel.setVisible(visible);
    }
    
    public void setVisibleCurseJComboBox(boolean visible) {
        this.curseJComboBox.setVisible(visible);
    }
    
    public void setVisibleCursoJLabel(boolean visible) {
        this.cursoJLabel.setVisible(visible);
    }
    
    public void addRolJComboBoxActionListener(ActionListener al) {
        this.rolJComboBox.addActionListener(al);
    }
    
    public void setVisibleRolJComboBox(boolean visible) {
        this.rolJComboBox.setVisible(visible);
    }
    
    public void setVisibleRolJLabel(boolean visible) {
        this.rolJLabel.setVisible(visible);
    }

    //telefonoJTextField  vtelefonoJLabel
    public void setVisibleTelefonoJTextField(boolean visible) {
        this.telefonoJTextField.setVisible(visible);
    }
    
    public void setVisibleTelefonoJLabel(boolean visible) {
        this.telefonoJLabel.setVisible(visible);
    }
    
    public String getTelefonoJTextField() {
        return this.telefonoJTextField.getText();
    }
    
    public void setTelefonoJTextField(String telefono) {
        this.telefonoJTextField.setText(telefono);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JComboBox<String> curseJComboBox;
    private javax.swing.JLabel cursoJLabel;
    private javax.swing.JLabel dataUserJLabel;
    private javax.swing.JComboBox<String> departamentoJComboBox;
    private javax.swing.JLabel departamentoJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel nameUserJLabel;
    private javax.swing.JTextField nameUserJTextField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPassword;
    private javax.swing.JComboBox<String> rolJComboBox;
    private javax.swing.JLabel rolJLabel;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel secondLastNameUserJLabel;
    private javax.swing.JTextField secondLastNameUserJTextField;
    private javax.swing.JLabel telefonoJLabel;
    private javax.swing.JTextField telefonoJTextField;
    // End of variables declaration//GEN-END:variables
}
