/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.login;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author nerea.salgado
 */
public class LoginJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public LoginJFrame() {
        initComponents();
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJButton = new javax.swing.JButton();
        loginImagenJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        PasswordJField = new javax.swing.JPasswordField();
        cancelJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));

        loginJButton.setText("Iniciar Sesión");
        loginJButton.addActionListener(this::loginJButtonActionPerformed);

        loginImagenJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nameJLabel.setText("Nombre:");

        passwordJLabel.setText("Contraseña:");

        cancelJButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginJButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordJLabel)
                                    .addComponent(nameJLabel))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(loginImagenJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(loginImagenJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(PasswordJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(cancelJButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginJButtonActionPerformed
    public void setTamanhoImage(int width, int height) {
        loginImagenJLabel.setSize(width, height);
    }

    public void getImagetoLabel(ImageIcon image) {
        int desiredWidth = 100;
        int desiredHeight = 100;

        Image newImage = image.getImage().getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
        loginImagenJLabel.setIcon(new ImageIcon(newImage));
    }

    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        cancelJButton.setBackground(new Color(231, 76, 60));
        cancelJButton.setForeground(Color.BLACK);
        cancelJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButton.setFocusPainted(false);
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        loginJButton.setBackground(new Color(46, 204, 113));
        loginJButton.setForeground(Color.BLACK);
        loginJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        loginJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        loginJButton.setFocusPainted(false);
        loginJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);
        Font campoFont = new Font("SansSerif", Font.PLAIN, 12);

        nameJLabel.setFont(labelFont);
        passwordJLabel.setFont(labelFont);

        nameJTextField.setFont(labelFont);
        nameJTextField.setBackground(blanco);
        nameJTextField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        PasswordJField.setFont(labelFont);
        PasswordJField.setBackground(blanco);
        PasswordJField.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        getContentPane().setBackground(grisFondo);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordJField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel loginImagenJLabel;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel passwordJLabel;
    // End of variables declaration//GEN-END:variables
}
