/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author nerea.salgado
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        applyStyles();
        setIconImage(new ImageIcon("src/main/resources/icono.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenInitJLabel = new javax.swing.JLabel();
        studentJButton = new javax.swing.JButton();
        teacherJButton = new javax.swing.JButton();
        adminJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentJButton.setText(" Alumno");

        teacherJButton.setText("Profesor");

        adminJButton.setText("Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenInitJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminJButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imagenInitJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentJButton)
                .addGap(18, 18, 18)
                .addComponent(teacherJButton)
                .addGap(18, 18, 18)
                .addComponent(adminJButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTamanhoImage(int width, int height) {
        imagenInitJLabel.setSize(width, height);
    }

    public void getImagetoLabel(ImageIcon image) {
        int desiredWidth = 100;
        int desiredHeight = 100;

        Image newImage = image.getImage().getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
        imagenInitJLabel.setIcon(new ImageIcon(newImage));
    }

    private void applyStyles() {

        studentJButton.setBackground(new Color(177, 189, 188));
        studentJButton.setForeground(Color.BLACK);
        studentJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        studentJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        studentJButton.setFocusPainted(false);
        studentJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        teacherJButton.setBackground(new Color(189, 183, 177));
        teacherJButton.setForeground(Color.BLACK);
        teacherJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        teacherJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        teacherJButton.setFocusPainted(false);
        teacherJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        adminJButton.setBackground(new Color(189, 177, 177));
        adminJButton.setForeground(Color.BLACK);
        adminJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        adminJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        adminJButton.setFocusPainted(false);
        adminJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    public void addStudentJButtonActionListener(ActionListener al) {
        this.studentJButton.addActionListener(al);
    }

    public void addTeacherJButtonActionListener(ActionListener al) {
        this.teacherJButton.addActionListener(al);
    }
    
    public void addAdminJButtonActionListener(ActionListener al){
        this.adminJButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminJButton;
    private javax.swing.JLabel imagenInitJLabel;
    private javax.swing.JButton studentJButton;
    private javax.swing.JButton teacherJButton;
    // End of variables declaration//GEN-END:variables

    
}
