/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.recomendation;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import view.student.StudentJDialog;

/**
 *
 * @author Nerea
 */
public class RecomendationToStudentJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecomendationToStudentJDialog.class.getName());

    /**
     * Creates new form RecomendationJDialog
     */
    public RecomendationToStudentJDialog(boolean modal, StudentJDialog view) {
        super(view, modal);
        initComponents();
        int rowIDLectura = recomendationJTable.getColumnCount() - 2;
        recomendationJTable.getColumnModel().getColumn(rowIDLectura).setMinWidth(0);
        recomendationJTable.getColumnModel().getColumn(rowIDLectura).setMaxWidth(0);
        recomendationJTable.getColumnModel().getColumn(rowIDLectura).setWidth(0);

        int rowIDProfesor = recomendationJTable.getColumnCount() - 1;
        recomendationJTable.getColumnModel().getColumn(rowIDProfesor).setMinWidth(0);
        recomendationJTable.getColumnModel().getColumn(rowIDProfesor).setMaxWidth(0);
        recomendationJTable.getColumnModel().getColumn(rowIDProfesor).setWidth(0);
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJlabel = new javax.swing.JLabel();
        addRecomendationJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recomendationJTable = new javax.swing.JTable();
        cancelJButton = new javax.swing.JButton();
        infoJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleJlabel.setText("Recomendaciones");

        addRecomendationJButton.setText("Añadir");

        recomendationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Profesor", "Comentario", "IDRecomendation", "IDProfesor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recomendationJTable);

        cancelJButton.setText("Cancelar");

        infoJButton.setText("Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJlabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cancelJButton)
                        .addGap(131, 131, 131)
                        .addComponent(infoJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addRecomendationJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJlabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(addRecomendationJButton)
                    .addComponent(infoJButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        addRecomendationJButton.setBackground(new Color(115, 222, 153));
        addRecomendationJButton.setForeground(Color.BLACK);
        addRecomendationJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        addRecomendationJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addRecomendationJButton.setFocusPainted(false);
        addRecomendationJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        infoJButton.setBackground(new Color(190, 190, 190));
        infoJButton.setForeground(Color.BLACK);
        infoJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        infoJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        infoJButton.setFocusPainted(false);
        infoJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        cancelJButton.setBackground(new Color(247, 181, 181));
        cancelJButton.setForeground(Color.BLACK);
        cancelJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButton.setFocusPainted(false);
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 18);

        titleJlabel.setFont(labelFont);
        titleJlabel.setFont(labelFont);
        titleJlabel.setFont(labelFont);
        titleJlabel.setForeground(new Color(102, 99, 98));
        titleJlabel.setFont(labelFont);

        getContentPane().setBackground(grisFondo);

    }

    public void addAddRecomendationJButton(ActionListener al) {
        this.addRecomendationJButton.addActionListener(al);
    }

    public void addInfoJButton(ActionListener al) {
        this.infoJButton.addActionListener(al);
    }

    public void addCancelJButton(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void addRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.recomendationJTable.getModel();
        model.addRow(row);
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.recomendationJTable.getModel();
        model.setRowCount(0);
        recomendationJTable.clearSelection();
        recomendationJTable.revalidate();
        recomendationJTable.repaint();
    }

    public String getInfo(int row, int col) {
        return recomendationJTable.getValueAt(row, col).toString();
    }

    public int getSelectedRow() {
        int select = recomendationJTable.getSelectedRow();
        return select;
    }

    public int getSelectedCol() {
        int select = recomendationJTable.getSelectedColumn();
        return select;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecomendationJButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JButton infoJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recomendationJTable;
    private javax.swing.JLabel titleJlabel;
    // End of variables declaration//GEN-END:variables
}
