/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.superAdmin;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nerea
 */
public class AdminsDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminsDialog.class.getName());

    /**
     * Creates new form AdminJDialog
     */
    public AdminsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        superAdminJTabbedPane = new javax.swing.JTabbedPane();
        usersJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersJTableUser = new javax.swing.JTable();
        addNewUserJButtonUser = new javax.swing.JButton();
        editUserJButtonUser = new javax.swing.JButton();
        deleteJButtonUser = new javax.swing.JButton();
        exportarTableJButtonUser = new javax.swing.JButton();
        IDBuscarJTextFieldUser = new javax.swing.JTextField();
        buscarJButtonUser = new javax.swing.JButton();
        curseJPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        curseJTableCurso = new javax.swing.JTable();
        nombreOrIDBuscarJTextFieldCurso = new javax.swing.JTextField();
        buscarJButtonCurso = new javax.swing.JButton();
        addNewCursoJButtonCurso = new javax.swing.JButton();
        editCursoJButtonCurso = new javax.swing.JButton();
        deleteJButtonCurso = new javax.swing.JButton();
        exportarTableJButtonCurso = new javax.swing.JButton();
        reportsJPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        librosMasRecomendadosJTabelReports = new javax.swing.JTable();
        exportarTableJButtonReports = new javax.swing.JButton();
        graficJPanelReports = new javax.swing.JPanel();
        booksJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksJTabelBooks = new javax.swing.JTable();
        addNewBookJButtonBooks = new javax.swing.JButton();
        editBookJButtonBook = new javax.swing.JButton();
        deleteJButtonBook = new javax.swing.JButton();
        tituloOrAutorBuscarJTextFieldBook = new javax.swing.JTextField();
        buscarJButtonBook = new javax.swing.JButton();
        exportarTableJButtonBooks = new javax.swing.JButton();
        superAdminJLabelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        usersJTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDUsuario", "Nombre", "Apellidos", "Correo", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(usersJTableUser);
        if (usersJTableUser.getColumnModel().getColumnCount() > 0) {
            usersJTableUser.getColumnModel().getColumn(2).setHeaderValue("Apellidos");
            usersJTableUser.getColumnModel().getColumn(3).setHeaderValue("Correo");
            usersJTableUser.getColumnModel().getColumn(4).setHeaderValue("Rol");
        }

        addNewUserJButtonUser.setText("Añadir");

        editUserJButtonUser.setText("Editar");

        deleteJButtonUser.setText("Eliminar");

        exportarTableJButtonUser.setText("Exportar");

        buscarJButtonUser.setText("buscar");

        javax.swing.GroupLayout usersJPanelLayout = new javax.swing.GroupLayout(usersJPanel);
        usersJPanel.setLayout(usersJPanelLayout);
        usersJPanelLayout.setHorizontalGroup(
            usersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersJPanelLayout.createSequentialGroup()
                        .addComponent(addNewUserJButtonUser)
                        .addGap(18, 18, 18)
                        .addComponent(editUserJButtonUser)
                        .addGap(18, 18, 18)
                        .addComponent(exportarTableJButtonUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteJButtonUser))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(IDBuscarJTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarJButtonUser)
                .addContainerGap())
        );
        usersJPanelLayout.setVerticalGroup(
            usersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDBuscarJTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarJButtonUser))
                    .addGroup(usersJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(usersJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addNewUserJButtonUser)
                            .addComponent(editUserJButtonUser)
                            .addComponent(exportarTableJButtonUser)
                            .addComponent(deleteJButtonUser))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        superAdminJTabbedPane.addTab("Usuarios", usersJPanel);

        curseJTableCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDCurso", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(curseJTableCurso);

        buscarJButtonCurso.setText("buscar");

        addNewCursoJButtonCurso.setText("Añadir");

        editCursoJButtonCurso.setText("Editar");

        deleteJButtonCurso.setText("Eliminar");

        exportarTableJButtonCurso.setText("Exportar");

        javax.swing.GroupLayout curseJPanelLayout = new javax.swing.GroupLayout(curseJPanel);
        curseJPanel.setLayout(curseJPanelLayout);
        curseJPanelLayout.setHorizontalGroup(
            curseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curseJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(curseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(curseJPanelLayout.createSequentialGroup()
                        .addComponent(addNewCursoJButtonCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCursoJButtonCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportarTableJButtonCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteJButtonCurso))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(nombreOrIDBuscarJTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buscarJButtonCurso)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        curseJPanelLayout.setVerticalGroup(
            curseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, curseJPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(curseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarJButtonCurso)
                    .addComponent(nombreOrIDBuscarJTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(curseJPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(curseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewCursoJButtonCurso)
                    .addComponent(editCursoJButtonCurso)
                    .addComponent(deleteJButtonCurso)
                    .addComponent(exportarTableJButtonCurso))
                .addGap(32, 32, 32))
        );

        superAdminJTabbedPane.addTab("Cursos", curseJPanel);

        librosMasRecomendadosJTabelReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Nº de leídos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(librosMasRecomendadosJTabelReports);

        exportarTableJButtonReports.setText("Exportar");

        javax.swing.GroupLayout graficJPanelReportsLayout = new javax.swing.GroupLayout(graficJPanelReports);
        graficJPanelReports.setLayout(graficJPanelReportsLayout);
        graficJPanelReportsLayout.setHorizontalGroup(
            graficJPanelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        graficJPanelReportsLayout.setVerticalGroup(
            graficJPanelReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout reportsJPanelLayout = new javax.swing.GroupLayout(reportsJPanel);
        reportsJPanel.setLayout(reportsJPanelLayout);
        reportsJPanelLayout.setHorizontalGroup(
            reportsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsJPanelLayout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addGroup(reportsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graficJPanelReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportarTableJButtonReports, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(reportsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportsJPanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(457, Short.MAX_VALUE)))
        );
        reportsJPanelLayout.setVerticalGroup(
            reportsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graficJPanelReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(exportarTableJButtonReports)
                .addContainerGap())
            .addGroup(reportsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportsJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );

        superAdminJTabbedPane.addTab("Informes", reportsJPanel);

        booksJTabelBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Título", "Autor", "Género", "Editorial", "Ejemplares"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(booksJTabelBooks);
        if (booksJTabelBooks.getColumnModel().getColumnCount() > 0) {
            booksJTabelBooks.getColumnModel().getColumn(5).setHeaderValue("Ejemplares");
        }

        addNewBookJButtonBooks.setText("Añadir");

        editBookJButtonBook.setText("Editar");

        deleteJButtonBook.setText("Eliminar");

        buscarJButtonBook.setText("buscar");

        exportarTableJButtonBooks.setText("Exportar");

        javax.swing.GroupLayout booksJPanelLayout = new javax.swing.GroupLayout(booksJPanel);
        booksJPanel.setLayout(booksJPanelLayout);
        booksJPanelLayout.setHorizontalGroup(
            booksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(booksJPanelLayout.createSequentialGroup()
                        .addComponent(addNewBookJButtonBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editBookJButtonBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exportarTableJButtonBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteJButtonBook))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tituloOrAutorBuscarJTextFieldBook, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarJButtonBook)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        booksJPanelLayout.setVerticalGroup(
            booksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, booksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tituloOrAutorBuscarJTextFieldBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarJButtonBook))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(booksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewBookJButtonBooks)
                    .addComponent(editBookJButtonBook)
                    .addComponent(deleteJButtonBook)
                    .addComponent(exportarTableJButtonBooks))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        superAdminJTabbedPane.addTab("Libros", booksJPanel);

        superAdminJLabelName.setText("Super admin: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(superAdminJLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superAdminJTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(superAdminJLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(superAdminJTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        Color azulAccion = new Color(164, 196, 235);
        Color amarilloValor = new Color(249, 231, 159);
        Color verde = new Color(168, 230, 207);
        Color naranjaUpdate = new Color(253, 203, 164);
        Color rojoBorrar = new Color(247, 181, 181);
        Color grisDetalles = new Color(213, 216, 220);
        Color grisFiltros = new Color(200, 200, 200);
        // =========== USERS =========

        buscarJButtonUser.setBackground(grisFiltros);
        buscarJButtonUser.setForeground(Color.BLACK);
        buscarJButtonUser.setFont(new Font("SansSerif", Font.BOLD, 12));
        buscarJButtonUser.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        buscarJButtonUser.setFocusPainted(false);
        buscarJButtonUser.setCursor(new Cursor(Cursor.HAND_CURSOR));

        deleteJButtonUser.setBackground(rojoBorrar);
        deleteJButtonUser.setForeground(Color.BLACK);
        deleteJButtonUser.setFont(new Font("SansSerif", Font.BOLD, 12));
        deleteJButtonUser.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        deleteJButtonUser.setFocusPainted(false);
        deleteJButtonUser.setCursor(new Cursor(Cursor.HAND_CURSOR));

        addNewUserJButtonUser.setBackground(verde);
        addNewUserJButtonUser.setForeground(Color.BLACK);
        addNewUserJButtonUser.setFont(new Font("SansSerif", Font.BOLD, 12));
        addNewUserJButtonUser.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addNewUserJButtonUser.setFocusPainted(false);
        addNewUserJButtonUser.setCursor(new Cursor(Cursor.HAND_CURSOR));

        exportarTableJButtonUser.setBackground(amarilloValor);
        exportarTableJButtonUser.setForeground(Color.BLACK);
        exportarTableJButtonUser.setFont(new Font("SansSerif", Font.BOLD, 12));
        exportarTableJButtonUser.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        exportarTableJButtonUser.setFocusPainted(false);
        exportarTableJButtonUser.setCursor(new Cursor(Cursor.HAND_CURSOR));

        editUserJButtonUser.setBackground(naranjaUpdate);
        editUserJButtonUser.setForeground(Color.BLACK);
        editUserJButtonUser.setFont(new Font("SansSerif", Font.BOLD, 12));
        editUserJButtonUser.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        editUserJButtonUser.setFocusPainted(false);
        editUserJButtonUser.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFontTitulo = new Font("SansSerif", Font.PLAIN, 18);
        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);
        superAdminJLabelName.setFont(labelFontTitulo);

        IDBuscarJTextFieldUser.setFont(labelFont);
        IDBuscarJTextFieldUser.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        // =========== CURSE =========
        buscarJButtonCurso.setBackground(grisFiltros);
        buscarJButtonCurso.setForeground(Color.BLACK);
        buscarJButtonCurso.setFont(new Font("SansSerif", Font.BOLD, 12));
        buscarJButtonCurso.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        buscarJButtonCurso.setFocusPainted(false);
        buscarJButtonCurso.setCursor(new Cursor(Cursor.HAND_CURSOR));

        deleteJButtonCurso.setBackground(rojoBorrar);
        deleteJButtonCurso.setForeground(Color.BLACK);
        deleteJButtonCurso.setFont(new Font("SansSerif", Font.BOLD, 12));
        deleteJButtonCurso.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        deleteJButtonCurso.setFocusPainted(false);
        deleteJButtonCurso.setCursor(new Cursor(Cursor.HAND_CURSOR));

        addNewCursoJButtonCurso.setBackground(verde);
        addNewCursoJButtonCurso.setForeground(Color.BLACK);
        addNewCursoJButtonCurso.setFont(new Font("SansSerif", Font.BOLD, 12));
        addNewCursoJButtonCurso.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addNewCursoJButtonCurso.setFocusPainted(false);
        addNewCursoJButtonCurso.setCursor(new Cursor(Cursor.HAND_CURSOR));

        exportarTableJButtonCurso.setBackground(amarilloValor);
        exportarTableJButtonCurso.setForeground(Color.BLACK);
        exportarTableJButtonCurso.setFont(new Font("SansSerif", Font.BOLD, 12));
        exportarTableJButtonCurso.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        exportarTableJButtonCurso.setFocusPainted(false);
        exportarTableJButtonCurso.setCursor(new Cursor(Cursor.HAND_CURSOR));

        editCursoJButtonCurso.setBackground(naranjaUpdate);
        editCursoJButtonCurso.setForeground(Color.BLACK);
        editCursoJButtonCurso.setFont(new Font("SansSerif", Font.BOLD, 12));
        editCursoJButtonCurso.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        editCursoJButtonCurso.setFocusPainted(false);
        editCursoJButtonCurso.setCursor(new Cursor(Cursor.HAND_CURSOR));

        nombreOrIDBuscarJTextFieldCurso.setFont(labelFont);
        nombreOrIDBuscarJTextFieldCurso.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        // =========== REPORTS =========
        exportarTableJButtonReports.setBackground(amarilloValor);
        exportarTableJButtonReports.setForeground(Color.BLACK);
        exportarTableJButtonReports.setFont(new Font("SansSerif", Font.BOLD, 12));
        exportarTableJButtonReports.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        exportarTableJButtonReports.setFocusPainted(false);
        exportarTableJButtonReports.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // =========== BOOKS =========
        buscarJButtonBook.setBackground(grisFiltros);
        buscarJButtonBook.setForeground(Color.BLACK);
        buscarJButtonBook.setFont(new Font("SansSerif", Font.BOLD, 12));
        buscarJButtonBook.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        buscarJButtonBook.setFocusPainted(false);
        buscarJButtonBook.setCursor(new Cursor(Cursor.HAND_CURSOR));

        addNewBookJButtonBooks.setBackground(verde);
        addNewBookJButtonBooks.setForeground(Color.BLACK);
        addNewBookJButtonBooks.setFont(new Font("SansSerif", Font.BOLD, 12));
        addNewBookJButtonBooks.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addNewBookJButtonBooks.setFocusPainted(false);
        addNewBookJButtonBooks.setCursor(new Cursor(Cursor.HAND_CURSOR));

        exportarTableJButtonBooks.setBackground(amarilloValor);
        exportarTableJButtonBooks.setForeground(Color.BLACK);
        exportarTableJButtonBooks.setFont(new Font("SansSerif", Font.BOLD, 12));
        exportarTableJButtonBooks.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        exportarTableJButtonBooks.setFocusPainted(false);
        exportarTableJButtonBooks.setCursor(new Cursor(Cursor.HAND_CURSOR));

        editBookJButtonBook.setBackground(naranjaUpdate);
        editBookJButtonBook.setForeground(Color.BLACK);
        editBookJButtonBook.setFont(new Font("SansSerif", Font.BOLD, 12));
        editBookJButtonBook.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        editBookJButtonBook.setFocusPainted(false);
        editBookJButtonBook.setCursor(new Cursor(Cursor.HAND_CURSOR));

        deleteJButtonBook.setBackground(rojoBorrar);
        deleteJButtonBook.setForeground(Color.BLACK);
        deleteJButtonBook.setFont(new Font("SansSerif", Font.BOLD, 12));
        deleteJButtonBook.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        deleteJButtonBook.setFocusPainted(false);
        deleteJButtonBook.setCursor(new Cursor(Cursor.HAND_CURSOR));

        tituloOrAutorBuscarJTextFieldBook.setFont(labelFont);
        tituloOrAutorBuscarJTextFieldBook.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(grisBorde), BorderFactory.createEmptyBorder(5, 8, 5, 8)));

        getContentPane().setBackground(grisFondo);

    }

    public void ocultarPestaña(int index) {
        superAdminJTabbedPane.removeTabAt(index);
    }

    public void setSuperAdminJLabelName(String name) {
        this.superAdminJLabelName.setText(name);
    }

    // =========== USERS =========+
    public void addRowUsers(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.usersJTableUser.getModel();
        model.addRow(row);
    }

    public void clearTableUsers() {
        DefaultTableModel model = (DefaultTableModel) this.usersJTableUser.getModel();
        model.setRowCount(0);
        usersJTableUser.clearSelection();
        usersJTableUser.revalidate();
        usersJTableUser.repaint();
    }

    public String getInfoUsers(int row, int col) {
        return usersJTableUser.getValueAt(row, col).toString();
    }

    public int getSelectedRowUsers() {
        int select = usersJTableUser.getSelectedRow();
        return select;
    }

    public int getSelectedColUsers() {
        int select = usersJTableUser.getSelectedColumn();
        return select;
    }

    public void addDeleteJButtonUserActionListener(ActionListener al) {
        this.deleteJButtonUser.addActionListener(al);
    }

    public void setVisibleJButtonExceptReportsExport(boolean visible){
        this.deleteJButtonBook.setVisible(visible);
        this.deleteJButtonCurso.setVisible(visible);
        this.deleteJButtonUser.setVisible(visible);
        
        this.addNewBookJButtonBooks.setVisible(visible);
        this.addNewCursoJButtonCurso.setVisible(visible);
        this.addNewUserJButtonUser.setVisible(visible);
        
        this.editBookJButtonBook.setVisible(visible);
        this.editCursoJButtonCurso.setVisible(visible);
        this.editUserJButtonUser.setVisible(visible);
    }
    
    public void addNewUserJButtonUserActionListener(ActionListener al) {
        this.addNewUserJButtonUser.addActionListener(al);
    }

    public void addEditUserJButtonUserActionListener(ActionListener al) {
        this.editUserJButtonUser.addActionListener(al);
    }

    public void addBuscarJButtonUserActionListener(ActionListener al) {
        this.buscarJButtonUser.addActionListener(al);
    }

    public String getNombreOrIDBuscarJTextFieldUser() {
        return this.IDBuscarJTextFieldUser.getText();
    }

    public void addExportarTableJButtonUserActionListener(ActionListener al) {
        this.exportarTableJButtonUser.addActionListener(al);
    }

    public JTable getTableUsersJTable() {
        return usersJTableUser;
    }

    // =========== CURSE =========
    public void addRowCurse(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.curseJTableCurso.getModel();
        model.addRow(row);
    }

    public void clearTableCurse() {
        DefaultTableModel model = (DefaultTableModel) this.curseJTableCurso.getModel();
        model.setRowCount(0);
        curseJTableCurso.clearSelection();
        curseJTableCurso.revalidate();
        curseJTableCurso.repaint();
    }

    public String getInfoCurse(int row, int col) {
        return curseJTableCurso.getValueAt(row, col).toString();
    }

    public int getSelectedRowCurse() {
        int select = curseJTableCurso.getSelectedRow();
        return select;
    }

    public int getSelectedColCurse() {
        int select = curseJTableCurso.getSelectedColumn();
        return select;
    }

    public void addNewCursoJButtonCursoActionListener(ActionListener al) {
        this.addNewCursoJButtonCurso.addActionListener(al);
    }

    public void addEditCursoJButtonCurso(ActionListener al) {
        this.editCursoJButtonCurso.addActionListener(al);
    }

    public void addDeleteJButtonCursoActionListener(ActionListener al) {
        this.deleteJButtonCurso.addActionListener(al);
    }

    public void addBuscarJButtonCursoActionListener(ActionListener al) {
        this.buscarJButtonCurso.addActionListener(al);
    }

    public String getNombreOrIDBuscarJTextFieldCurso() {
        return this.nombreOrIDBuscarJTextFieldCurso.getText();
    }

    public JTable getTableCurseJTable() {
        return curseJTableCurso;
    }

    public void addExportarTableJButtonCursoActionListener(ActionListener al) {
        this.exportarTableJButtonCurso.addActionListener(al);
    }

    // =========== INFORMES ========= librosMasRecomendadosJTabelReports
    public void addRowInforme(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.librosMasRecomendadosJTabelReports.getModel();
        model.addRow(row);
    }

    public void clearTableCurseInforme() {
        DefaultTableModel model = (DefaultTableModel) this.librosMasRecomendadosJTabelReports.getModel();
        model.setRowCount(0);
        librosMasRecomendadosJTabelReports.clearSelection();
        librosMasRecomendadosJTabelReports.revalidate();
        librosMasRecomendadosJTabelReports.repaint();
    }

    public String getInfoCurseInforme(int row, int col) {
        return librosMasRecomendadosJTabelReports.getValueAt(row, col).toString();
    }

    public int getSelectedRowCurseInforme() {
        int select = librosMasRecomendadosJTabelReports.getSelectedRow();
        return select;
    }

    public int getSelectedColCurseInforme() {
        int select = librosMasRecomendadosJTabelReports.getSelectedColumn();
        return select;
    }

    public void addExportarTableJButtonReportsActionListener(ActionListener al) {
        this.exportarTableJButtonReports.addActionListener(al);
    }

    public JTable getTableInformeJTable() {
        return librosMasRecomendadosJTabelReports;
    }

    public void limpiarGraficJPanelReports() {
        this.graficJPanelReports.removeAll();
        this.graficJPanelReports.revalidate();
        this.graficJPanelReports.repaint();
    }

    public void addGraficaGraficJPanelReports(JPanel panel) {
        this.graficJPanelReports.setLayout(new BorderLayout());
        this.graficJPanelReports.add(panel, BorderLayout.CENTER);
        this.graficJPanelReports.revalidate();
        this.graficJPanelReports.repaint();

    }

    // booksJTabelBooks =========== BOOKS =========
    public void addRowBooks(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.booksJTabelBooks.getModel();
        model.addRow(row);
    }

    public void clearTableBooks() {
        DefaultTableModel model = (DefaultTableModel) this.booksJTabelBooks.getModel();
        model.setRowCount(0);
        booksJTabelBooks.clearSelection();
        booksJTabelBooks.revalidate();
        booksJTabelBooks.repaint();
    }

    public String getInfoBooks(int row, int col) {
        return booksJTabelBooks.getValueAt(row, col).toString();
    }

    public int getSelectedRowBooks() {
        int select = booksJTabelBooks.getSelectedRow();
        return select;
    }

    public int getSelectedColBooks() {
        int select = booksJTabelBooks.getSelectedColumn();
        return select;
    }

    public void addNewBookJButtonBooksActionListener(ActionListener al) {
        this.addNewBookJButtonBooks.addActionListener(al);
    }

    public void addEditBookJButtonBookActionListener(ActionListener al) {
        this.editBookJButtonBook.addActionListener(al);
    }

    public void addDeleteJButtonBookActionListener(ActionListener al) {
        this.deleteJButtonBook.addActionListener(al);
    }

    public void addExportarTableJButtonBooksActionListener(ActionListener al) {
        this.exportarTableJButtonBooks.addActionListener(al);
    }

    public JTable getTabeBooksJTable() {
        return booksJTabelBooks;
    }

    public void addBuscarJButtonBookActionListener(ActionListener al) {
        this.buscarJButtonBook.addActionListener(al);
    }

    public String getTituloOrAutorBuscarJTextFieldBook() {
        return this.tituloOrAutorBuscarJTextFieldBook.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDBuscarJTextFieldUser;
    private javax.swing.JButton addNewBookJButtonBooks;
    private javax.swing.JButton addNewCursoJButtonCurso;
    private javax.swing.JButton addNewUserJButtonUser;
    private javax.swing.JPanel booksJPanel;
    private javax.swing.JTable booksJTabelBooks;
    private javax.swing.JButton buscarJButtonBook;
    private javax.swing.JButton buscarJButtonCurso;
    private javax.swing.JButton buscarJButtonUser;
    private javax.swing.JPanel curseJPanel;
    private javax.swing.JTable curseJTableCurso;
    private javax.swing.JButton deleteJButtonBook;
    private javax.swing.JButton deleteJButtonCurso;
    private javax.swing.JButton deleteJButtonUser;
    private javax.swing.JButton editBookJButtonBook;
    private javax.swing.JButton editCursoJButtonCurso;
    private javax.swing.JButton editUserJButtonUser;
    private javax.swing.JButton exportarTableJButtonBooks;
    private javax.swing.JButton exportarTableJButtonCurso;
    private javax.swing.JButton exportarTableJButtonReports;
    private javax.swing.JButton exportarTableJButtonUser;
    private javax.swing.JPanel graficJPanelReports;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable librosMasRecomendadosJTabelReports;
    private javax.swing.JTextField nombreOrIDBuscarJTextFieldCurso;
    private javax.swing.JPanel reportsJPanel;
    private javax.swing.JLabel superAdminJLabelName;
    private javax.swing.JTabbedPane superAdminJTabbedPane;
    private javax.swing.JTextField tituloOrAutorBuscarJTextFieldBook;
    private javax.swing.JPanel usersJPanel;
    private javax.swing.JTable usersJTableUser;
    // End of variables declaration//GEN-END:variables
}
