/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.teacher;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nerea
 */
public class TeacherJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeacherJDialog.class.getName());

    /**
     * Creates new form TeacherJDialog
     */
    public TeacherJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherJLabel = new javax.swing.JLabel();
        curseJComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        informeJButton = new javax.swing.JButton();
        booksListJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        teacherJLabel.setText("Profesor");

        curseJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Cursos");

        studentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumno", "Apellido", "Curso", "Libros leidos", "Libros pendientes", "Libros sin leer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentsJTable);

        jLabel2.setText("Estudiantes");

        informeJButton.setText("Ver informe");

        booksListJButton.setText("Libros Disponibles ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(teacherJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(curseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(booksListJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(informeJButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(394, 394, 394)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informeJButton)
                    .addComponent(booksListJButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        Color azulAccion = new Color(164, 196, 235);
        Color amarilloValor = new Color(249, 231, 159);
        Color verdeComent = new Color(168, 230, 207);
        Color naranjaUpdate = new Color(253, 203, 164);
        Color rojoBorrar = new Color(247, 181, 181);
        Color grisDetalles = new Color(213, 216, 220);
        Color grisFiltros = new Color(200, 200, 200);

        // Botón Detalles lectura
        booksListJButton.setBackground(amarilloValor);
        booksListJButton.setForeground(Color.BLACK);
        booksListJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        booksListJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        booksListJButton.setFocusPainted(false);
        booksListJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Recomendaciones
        informeJButton.setBackground(grisDetalles);
        informeJButton.setForeground(Color.BLACK);
        informeJButton.setFont(new Font("SansSerif", Font.PLAIN, 12));
        informeJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        informeJButton.setFocusPainted(false);
        informeJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 18);
        teacherJLabel.setFont(labelFont);
        teacherJLabel.setForeground(new Color(102, 99, 98));

        getContentPane().setBackground(grisFondo);
    }

    public void setNameTeacherJLabel(String name) {
        this.teacherJLabel.setText(name);
    }

    public void addInformeJButtonActionListener(ActionListener al) {
        this.informeJButton.addActionListener(al);
    }

    public void addCurseJComboBoxActionListener(ActionListener al) {
        this.curseJComboBox.addActionListener(al);
    }

    public void booksListJButtonActionListener(ActionListener al) {
        this.booksListJButton.addActionListener(al);
    }

    public void addRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.studentsJTable.getModel();
        model.addRow(row);
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.studentsJTable.getModel();
        model.setRowCount(0);
        studentsJTable.clearSelection();
        studentsJTable.revalidate();
        studentsJTable.repaint();
    }

    public String getInfo(int row, int col) {
        return studentsJTable.getValueAt(row, col).toString();
    }

    public int getSelectedRow() {
        int select = studentsJTable.getSelectedRow();
        return select;
    }

    public int getSelectedCol() {
        int select = studentsJTable.getSelectedColumn();
        return select;
    }

    public void addItemsCurseJComboBox(String nombreCurso) {
        this.curseJComboBox.addItem(nombreCurso);
    }

    public void clearCurseJComboBox() {
        this.curseJComboBox.removeAllItems();
    }

    public String getCurseJComboBox() {
        return this.curseJComboBox.getSelectedItem().toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booksListJButton;
    private javax.swing.JComboBox<String> curseJComboBox;
    private javax.swing.JButton informeJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentsJTable;
    private javax.swing.JLabel teacherJLabel;
    // End of variables declaration//GEN-END:variables
}
