/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.student;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nerea
 */
public class StudentJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentJDialog.class.getName());

    /**
     * Creates new form StudenJDialog
     */
    public StudentJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        int rowIDLectura = booskJTable.getColumnCount() - 1;
        booskJTable.getColumnModel().getColumn(rowIDLectura).setMinWidth(0);
        booskJTable.getColumnModel().getColumn(rowIDLectura).setMaxWidth(0);
        booskJTable.getColumnModel().getColumn(rowIDLectura).setWidth(0);
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        booskJTable = new javax.swing.JTable();
        changeStateJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        alorationJButton = new javax.swing.JButton();
        addComentJButton = new javax.swing.JButton();
        updatePageJButton = new javax.swing.JButton();
        recomendationsJButton = new javax.swing.JButton();
        detailsBookJButton = new javax.swing.JButton();
        studentJLabel = new javax.swing.JLabel();
        detailsLectureJButton = new javax.swing.JButton();
        readAndNotJButton = new javax.swing.JButton();
        pendingJButton = new javax.swing.JButton();
        readingJButton = new javax.swing.JButton();
        booksInAvailable = new javax.swing.JButton();
        changeDateJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        booskJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Fecha_Inicio", "Fecha_Fin", "Páginas_Leídas", "Valoración", "Comentario", "Título Libro", "Nombre Profesor", "IDLectura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(booskJTable);

        changeStateJButton.setText("🔄 Estado");

        deleteJButton.setText("Borrar");

        alorationJButton.setText("🖊️ ️ Valoración");

        addComentJButton.setText("⭐ Comentario");

        updatePageJButton.setText("🖊️ ️ Páginas");

        recomendationsJButton.setText("Recomendaciones");

        detailsBookJButton.setText("🔍 Libro");

        studentJLabel.setText("Estudiante");

        detailsLectureJButton.setText("🔍 Lectura");

        readAndNotJButton.setText("✅ Leidos");

        pendingJButton.setText("📌 Pendientes");

        readingJButton.setText("📖 Leyendo");
        readingJButton.addActionListener(this::readingJButtonActionPerformed);

        booksInAvailable.setText("📖 Disponibles");

        changeDateJButton.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changeStateJButton)
                                .addGap(18, 18, 18)
                                .addComponent(alorationJButton)
                                .addGap(18, 18, 18)
                                .addComponent(updatePageJButton)
                                .addGap(18, 18, 18)
                                .addComponent(addComentJButton)
                                .addGap(18, 18, 18)
                                .addComponent(booksInAvailable)
                                .addGap(18, 18, 18)
                                .addComponent(changeDateJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(recomendationsJButton)
                                .addGap(18, 18, 18)
                                .addComponent(detailsLectureJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(detailsBookJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                        .addComponent(readingJButton)
                        .addGap(18, 18, 18)
                        .addComponent(readAndNotJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pendingJButton)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readAndNotJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeStateJButton)
                            .addComponent(alorationJButton)
                            .addComponent(updatePageJButton)
                            .addComponent(addComentJButton)
                            .addComponent(booksInAvailable)
                            .addComponent(changeDateJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(deleteJButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recomendationsJButton)
                    .addComponent(detailsLectureJButton)
                    .addComponent(detailsBookJButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readingJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readingJButtonActionPerformed
    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        // Colores profesionales para botones
        Color azulAccion = new Color(164, 196, 235);
        Color amarilloValor = new Color(249, 231, 159);
        Color verdeComent = new Color(168, 230, 207);
        Color naranjaUpdate = new Color(253, 203, 164);
        Color rojoBorrar = new Color(247, 181, 181);
        Color grisDetalles = new Color(213, 216, 220);
        Color grisFiltros = new Color(200, 200, 200);

        // Botón Añadir comentario
        addComentJButton.setBackground(verdeComent);
        addComentJButton.setForeground(Color.BLACK);
        addComentJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        addComentJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        addComentJButton.setFocusPainted(false);
        addComentJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón ver todos los libros
        booksInAvailable.setBackground(grisBorde);
        booksInAvailable.setForeground(Color.BLACK);
        booksInAvailable.setFont(new Font("SansSerif", Font.BOLD, 12));
        booksInAvailable.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        booksInAvailable.setFocusPainted(false);
        booksInAvailable.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Actualizar páginas
        updatePageJButton.setBackground(naranjaUpdate);
        updatePageJButton.setForeground(Color.BLACK);
        updatePageJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        updatePageJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        updatePageJButton.setFocusPainted(false);
        updatePageJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Añadir valoración
        alorationJButton.setBackground(amarilloValor);
        alorationJButton.setForeground(Color.BLACK);
        alorationJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        alorationJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        alorationJButton.setFocusPainted(false);
        alorationJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Cambiar estado
        changeStateJButton.setBackground(azulAccion);
        changeStateJButton.setForeground(Color.BLACK);
        changeStateJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        changeStateJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        changeStateJButton.setFocusPainted(false);
        changeStateJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Detalles libro
        detailsBookJButton.setBackground(grisDetalles);
        detailsBookJButton.setForeground(Color.BLACK);
        detailsBookJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        detailsBookJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        detailsBookJButton.setFocusPainted(false);
        detailsBookJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Detalles lectura
        detailsLectureJButton.setBackground(grisDetalles);
        detailsLectureJButton.setForeground(Color.BLACK);
        detailsLectureJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        detailsLectureJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        detailsLectureJButton.setFocusPainted(false);
        detailsLectureJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Recomendaciones
        recomendationsJButton.setBackground(grisDetalles);
        recomendationsJButton.setForeground(Color.BLACK);
        recomendationsJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        recomendationsJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        recomendationsJButton.setFocusPainted(false);
        recomendationsJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botón Borrar
        deleteJButton.setBackground(rojoBorrar);
        deleteJButton.setForeground(Color.BLACK);
        deleteJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        deleteJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        deleteJButton.setFocusPainted(false);
        deleteJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Botones de filtros (color gris por defecto)
        readAndNotJButton.setBackground(grisFiltros);
        readAndNotJButton.setForeground(Color.BLACK);
        readAndNotJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        readAndNotJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        readAndNotJButton.setFocusPainted(false);
        readAndNotJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        readingJButton.setBackground(grisFiltros);
        readingJButton.setForeground(Color.BLACK);
        readingJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        readingJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        readingJButton.setFocusPainted(false);
        readingJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        pendingJButton.setBackground(grisFiltros);
        pendingJButton.setForeground(Color.BLACK);
        pendingJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        pendingJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        pendingJButton.setFocusPainted(false);
        pendingJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        changeDateJButton.setBackground(azulAccion);
        changeDateJButton.setForeground(Color.BLACK);
        changeDateJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        changeDateJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        changeDateJButton.setFocusPainted(false);
        changeDateJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 18);
        studentJLabel.setFont(labelFont);
        studentJLabel.setForeground(new Color(102, 99, 98));

        getContentPane().setBackground(grisFondo);
    }

    public void changeDateJButtonActionListener(ActionListener al) {
        this.changeDateJButton.addActionListener(al);
    }

    public void addRecomendationsJButton(ActionListener al) {
        this.recomendationsJButton.addActionListener(al);
    }

    public void addBooksInAvailableJButton(ActionListener al) {
        this.booksInAvailable.addActionListener(al);
    }

    public void addValorationJButton(ActionListener al) {
        this.alorationJButton.addActionListener(al);
    }

    public void addDetailsBookJButtonActionListener(ActionListener al) {
        this.detailsBookJButton.addActionListener(al);
    }

    public void addRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.booskJTable.getModel();
        model.addRow(row);
    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.booskJTable.getModel();
        model.setRowCount(0);
        booskJTable.clearSelection();
        booskJTable.revalidate();
        booskJTable.repaint();
    }

    public String getInfo(int row, int col) {
       Object value = booskJTable.getValueAt(row, col);
       if(value == null){
           return "";
       }
       return value.toString();
    }

    public int getSelectedRow() {
        int select = booskJTable.getSelectedRow();
        return select;
    }

    public int getSelectedCol() {
        int select = booskJTable.getSelectedColumn();
        return select;
    }

    public void changeColorReadAndNotJButton(Color color) {
        this.readAndNotJButton.setBackground(color);
        readAndNotJButton.setForeground(Color.BLACK);
        readAndNotJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        readAndNotJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        readAndNotJButton.setFocusPainted(false);
        readAndNotJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public void changeColorReadingJButton(Color color) {
        this.readingJButton.setBackground(color);
        readingJButton.setForeground(Color.BLACK);
        readingJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        readingJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        readingJButton.setFocusPainted(false);
        readingJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public void changeColorPendingJButton(Color color) {
        this.pendingJButton.setBackground(color);
        pendingJButton.setForeground(Color.BLACK);
        pendingJButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        pendingJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        pendingJButton.setFocusPainted(false);
        pendingJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public void addReadAndNotJButtonActionListener(ActionListener al) {
        this.readAndNotJButton.addActionListener(al);
    }

    public void addReadingJButtonActionListener(ActionListener al) {
        this.readingJButton.addActionListener(al);
    }

    public void addChekReadJButtonActionListener(ActionListener al) {
        this.changeStateJButton.addActionListener(al);
    }

    public void addPendingJButtonActionListener(ActionListener al) {
        this.pendingJButton.addActionListener(al);
    }

    public void setStudentJLabel(String nombreAlumno) {
        this.studentJLabel.setText(nombreAlumno);
    }

    public void addDetailsLectureJButtonActionListener(ActionListener al) {
        this.detailsLectureJButton.addActionListener(al);
    }

    public void addComentJButtonActionListener(ActionListener al) {
        this.addComentJButton.addActionListener(al);
    }

    public void addUpdatePageJButton(ActionListener al) {
        this.updatePageJButton.addActionListener(al);
    }

    public void addDeleteJButton(ActionListener al) {
        this.deleteJButton.addActionListener(al);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComentJButton;
    private javax.swing.JButton alorationJButton;
    private javax.swing.JButton booksInAvailable;
    private javax.swing.JTable booskJTable;
    private javax.swing.JButton changeDateJButton;
    private javax.swing.JButton changeStateJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JButton detailsBookJButton;
    private javax.swing.JButton detailsLectureJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pendingJButton;
    private javax.swing.JButton readAndNotJButton;
    private javax.swing.JButton readingJButton;
    private javax.swing.JButton recomendationsJButton;
    private javax.swing.JLabel studentJLabel;
    private javax.swing.JButton updatePageJButton;
    // End of variables declaration//GEN-END:variables
}
