/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.reportsTeacher;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;
import view.teacher.TeacherJDialog;

/**
 *
 * @author Nerea
 */
public class ReportsTeacherJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsTeacherJDialog.class.getName());

    /**
     * Creates new form ReportsTeacherJDialog
     */
    public ReportsTeacherJDialog(boolean modal, TeacherJDialog view) {
        super(view, modal);
        initComponents();
        applyStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        booksMostValorationJPanel = new javax.swing.JPanel();
        cursoJLabelValoration = new javax.swing.JLabel();
        cursoJComboBoxValoration = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableValorationJTableValoration = new javax.swing.JTable();
        exportJButtonValoration = new javax.swing.JButton();
        cancelJButtonValoration = new javax.swing.JButton();
        booksReadForStudentPanel = new javax.swing.JPanel();
        cursoJLabelBooks = new javax.swing.JLabel();
        cursoJComboBoxBooks = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBooksTableBooks = new javax.swing.JTable();
        cancelJButtonBooks = new javax.swing.JButton();
        exportJButtonExportBooks = new javax.swing.JButton();
        studentJLabelBooks = new javax.swing.JLabel();
        studentJComboBoxBooks = new javax.swing.JComboBox<>();
        booksReadGraficForStudentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cursoJLabelValoration.setText("Curso:");

        cursoJComboBoxValoration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tableValorationJTableValoration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableValorationJTableValoration);

        exportJButtonValoration.setText("Exportar");

        cancelJButtonValoration.setText("Cancelar");

        javax.swing.GroupLayout booksMostValorationJPanelLayout = new javax.swing.GroupLayout(booksMostValorationJPanel);
        booksMostValorationJPanel.setLayout(booksMostValorationJPanelLayout);
        booksMostValorationJPanelLayout.setHorizontalGroup(
            booksMostValorationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksMostValorationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booksMostValorationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(booksMostValorationJPanelLayout.createSequentialGroup()
                        .addGroup(booksMostValorationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(booksMostValorationJPanelLayout.createSequentialGroup()
                                .addComponent(cursoJLabelValoration)
                                .addGap(18, 18, 18)
                                .addComponent(cursoJComboBoxValoration, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(386, 386, 386))
                            .addGroup(booksMostValorationJPanelLayout.createSequentialGroup()
                                .addComponent(cancelJButtonValoration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 975, Short.MAX_VALUE)
                                .addComponent(exportJButtonValoration)))
                        .addContainerGap())
                    .addGroup(booksMostValorationJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(14, 14, 14))))
        );
        booksMostValorationJPanelLayout.setVerticalGroup(
            booksMostValorationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksMostValorationJPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(booksMostValorationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoJComboBoxValoration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursoJLabelValoration))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(booksMostValorationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportJButtonValoration)
                    .addComponent(cancelJButtonValoration))
                .addGap(16, 16, 16))
        );

        TabbedPane.addTab("Libros mas valorados", booksMostValorationJPanel);

        cursoJLabelBooks.setText("Curso:");

        cursoJComboBoxBooks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tableBooksTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Estado", "Valoración", "Inicio lectura", "Fin lectura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableBooksTableBooks);

        cancelJButtonBooks.setText("Cancelar");

        exportJButtonExportBooks.setText("Exportar");

        studentJLabelBooks.setText("Alumno:");

        studentJComboBoxBooks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout booksReadGraficForStudentPanelLayout = new javax.swing.GroupLayout(booksReadGraficForStudentPanel);
        booksReadGraficForStudentPanel.setLayout(booksReadGraficForStudentPanelLayout);
        booksReadGraficForStudentPanelLayout.setHorizontalGroup(
            booksReadGraficForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        booksReadGraficForStudentPanelLayout.setVerticalGroup(
            booksReadGraficForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout booksReadForStudentPanelLayout = new javax.swing.GroupLayout(booksReadForStudentPanel);
        booksReadForStudentPanel.setLayout(booksReadForStudentPanelLayout);
        booksReadForStudentPanelLayout.setHorizontalGroup(
            booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksReadForStudentPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(booksReadForStudentPanelLayout.createSequentialGroup()
                        .addComponent(cursoJLabelBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cursoJComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(studentJLabelBooks)
                        .addGap(53, 53, 53)
                        .addComponent(studentJComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(booksReadForStudentPanelLayout.createSequentialGroup()
                            .addComponent(cancelJButtonBooks)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exportJButtonExportBooks))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(booksReadGraficForStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        booksReadForStudentPanelLayout.setVerticalGroup(
            booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksReadForStudentPanelLayout.createSequentialGroup()
                .addGroup(booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(booksReadForStudentPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentJComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cursoJLabelBooks)
                                .addComponent(cursoJComboBoxBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studentJLabelBooks)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, booksReadForStudentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(booksReadGraficForStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(booksReadForStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportJButtonExportBooks)
                    .addComponent(cancelJButtonBooks))
                .addGap(14, 14, 14))
        );

        TabbedPane.addTab("Seguimiento lecturas por alumno", booksReadForStudentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyStyles() {
        Color grisFondo = new Color(245, 247, 250);
        Color grisBorde = new Color(200, 200, 200);
        Color blanco = Color.WHITE;

        Color azulAccion = new Color(164, 196, 235);
        Color amarilloValor = new Color(249, 231, 159);
        Color verdeComent = new Color(168, 230, 207);
        Color naranjaUpdate = new Color(253, 203, 164);
        Color rojoBorrar = new Color(247, 181, 181);
        Color grisDetalles = new Color(213, 216, 220);
        Color grisFiltros = new Color(200, 200, 200);

        cancelJButtonValoration.setBackground(rojoBorrar);
        cancelJButtonValoration.setForeground(Color.BLACK);
        cancelJButtonValoration.setFont(new Font("SansSerif", Font.PLAIN, 12));
        cancelJButtonValoration.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButtonValoration.setFocusPainted(false);
        cancelJButtonValoration.setCursor(new Cursor(Cursor.HAND_CURSOR));

        cancelJButtonBooks.setBackground(rojoBorrar);
        cancelJButtonBooks.setForeground(Color.BLACK);
        cancelJButtonBooks.setFont(new Font("SansSerif", Font.PLAIN, 12));
        cancelJButtonBooks.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        cancelJButtonBooks.setFocusPainted(false);
        cancelJButtonBooks.setCursor(new Cursor(Cursor.HAND_CURSOR));

        exportJButtonExportBooks.setBackground(verdeComent);
        exportJButtonExportBooks.setForeground(Color.BLACK);
        exportJButtonExportBooks.setFont(new Font("SansSerif", Font.PLAIN, 12));
        exportJButtonExportBooks.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        exportJButtonExportBooks.setFocusPainted(false);
        exportJButtonExportBooks.setCursor(new Cursor(Cursor.HAND_CURSOR));

        exportJButtonValoration.setBackground(verdeComent);
        exportJButtonValoration.setForeground(Color.BLACK);
        exportJButtonValoration.setFont(new Font("SansSerif", Font.PLAIN, 12));
        exportJButtonValoration.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));
        exportJButtonValoration.setFocusPainted(false);
        exportJButtonValoration.setCursor(new Cursor(Cursor.HAND_CURSOR));

        Font labelFont = new Font("SansSerif", Font.PLAIN, 18);
        cursoJLabelValoration.setFont(labelFont);
        cursoJLabelValoration.setForeground(new Color(102, 99, 98));

        getContentPane().setBackground(grisFondo);
    }

    //BOOKS
    public void addRowTableBooksTable1(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.tableBooksTableBooks.getModel();
        model.addRow(row);
    }

    public void clearTableBooksTable1() {
        DefaultTableModel model = (DefaultTableModel) this.tableBooksTableBooks.getModel();
        model.setRowCount(0);
        tableBooksTableBooks.clearSelection();
        tableBooksTableBooks.revalidate();
        tableBooksTableBooks.repaint();
    }

    public String getInfoTableBooksTable1(int row, int col) {
        return tableBooksTableBooks.getValueAt(row, col).toString();
    }

    public int getSelectedRowTableBooksTable1() {
        int select = tableBooksTableBooks.getSelectedRow();
        return select;
    }

    public int getSelectedColTableBooksTable1() {
        int select = tableBooksTableBooks.getSelectedColumn();
        return select;
    }

    public void addItemsCurseJComboBoxBooks(String nombreCurso) {
        this.cursoJComboBoxBooks.addItem(nombreCurso);
    }

    public void clearCurseJComboBoxBooks() {
        this.cursoJComboBoxBooks.removeAllItems();
    }

    public String getCurseJComboBoxBooks() {
        return this.cursoJComboBoxBooks.getSelectedItem().toString();
    }

    public void addExportJButtonBooksActionListener(ActionListener al) {
        this.exportJButtonExportBooks.addActionListener(al);
    }

    public void addCancelJButtonBooksActionListener(ActionListener al) {
        this.cancelJButtonBooks.addActionListener(al);
    }

    public void addItemsStudentsJComboBoxBooks(String nombreCurso) {
        this.studentJComboBoxBooks.addItem(nombreCurso);
    }

    public void clearStudentsJComboBoxBooks() {
        this.studentJComboBoxBooks.removeAllItems();
    }

    public String getStudentsJComboBoxBooks() {
        return this.studentJComboBoxBooks.getSelectedItem().toString();
    }

    public void addCursoJComboBoxBooksActionListener(ActionListener al) {
        this.cursoJComboBoxBooks.addActionListener(al);
    }

    public void addStudentJComboBoxBooksActionListener(ActionListener al) {
        this.studentJComboBoxBooks.addActionListener(al);
    }

    public int getStudentJComboBoxBookIndex() {
        return this.studentJComboBoxBooks.getSelectedIndex();
    }

    public void addCancelJButtonValorationActionListener(ActionListener al) {
        this.cancelJButtonValoration.addActionListener(al);
    }

    //VALORATION
    public void addCursoJComboBoxValorationActionListener(ActionListener al) {
        this.cursoJComboBoxValoration.addActionListener(al);
    }

    public void addRowtableValorationJTable(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.tableValorationJTableValoration.getModel();
        model.addRow(row);
    }

    public void clearTableValorationJTable() {
        DefaultTableModel model = (DefaultTableModel) this.tableValorationJTableValoration.getModel();
        model.setRowCount(0);
        tableValorationJTableValoration.clearSelection();
        tableValorationJTableValoration.revalidate();
        tableValorationJTableValoration.repaint();
    }

    public String getInfoTableValorationJTable(int row, int col) {
        return tableValorationJTableValoration.getValueAt(row, col).toString();
    }

    public int getSelectedRowTableValorationJTable() {
        int select = tableValorationJTableValoration.getSelectedRow();
        return select;
    }

    public int getSelectedColTableValorationJTable() {
        int select = tableValorationJTableValoration.getSelectedColumn();
        return select;
    }

    public void addItemsCurseJComboBoxValoration(String nombreCurso) {
        this.cursoJComboBoxValoration.addItem(nombreCurso);
    }

    public void clearCurseJComboBoxValoration() {
        this.cursoJComboBoxValoration.removeAllItems();
    }

    public String getCurseJComboBoxValoration() {
        return this.cursoJComboBoxValoration.getSelectedItem().toString();
    }

    public void addExportJButtonValorationActionListener(ActionListener al) {
        this.exportJButtonValoration.addActionListener(al);
    }

    public JTable getTableValorationJTableValoration() {
        return tableValorationJTableValoration;
    }

    public JTable getTableBooksTableBooks() {
        return tableBooksTableBooks;
    }

    public int getTableValorationRowCount() {
        return tableValorationJTableValoration.getRowCount();
    }

    public void limpiarBooksReadGraficForStudentPanel() {
        this.booksReadGraficForStudentPanel.removeAll();
        this.booksReadGraficForStudentPanel.revalidate();
        this.booksReadGraficForStudentPanel.repaint();
    }

    public void addGraficaEnBooksReadGraficForStudentPanel(JPanel panel) {
        this.booksReadGraficForStudentPanel.setLayout(new BorderLayout());
        this.booksReadGraficForStudentPanel.add(panel, BorderLayout.CENTER);
        this.booksReadGraficForStudentPanel.revalidate();
        this.booksReadGraficForStudentPanel.repaint();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel booksMostValorationJPanel;
    private javax.swing.JPanel booksReadForStudentPanel;
    private javax.swing.JPanel booksReadGraficForStudentPanel;
    private javax.swing.JButton cancelJButtonBooks;
    private javax.swing.JButton cancelJButtonValoration;
    private javax.swing.JComboBox<String> cursoJComboBoxBooks;
    private javax.swing.JComboBox<String> cursoJComboBoxValoration;
    private javax.swing.JLabel cursoJLabelBooks;
    private javax.swing.JLabel cursoJLabelValoration;
    private javax.swing.JButton exportJButtonExportBooks;
    private javax.swing.JButton exportJButtonValoration;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> studentJComboBoxBooks;
    private javax.swing.JLabel studentJLabelBooks;
    private javax.swing.JTable tableBooksTableBooks;
    private javax.swing.JTable tableValorationJTableValoration;
    // End of variables declaration//GEN-END:variables
}
